In [5]:
import numpy as np
from scipy import io
import scipy.cluster
import matplotlib.pyplot as plt

In [6]:
mnist = io.loadmat("data/mnist_data.mat")
mnist_x = mnist["training_data"]
mnist_y = mnist["training_labels"]
mnist_test = mnist["test_data"]
mnist_x = scipy.cluster.vq.whiten(mnist_x)
# x, y, val_data, val_label = train_val_split(mnist_x, mnist_y, 10000)

In [17]:
class1 = mnist_x[(mnist_y == 1).flatten()]
mean = np.mean(class1)

In [24]:
np.cov(class1.T, bias = True).shape

(784, 784)

In [23]:
np.dot((class1-mean).T, (class1-mean))/class1.shape[0]

array([[0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237],
       [0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237],
       [0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237],
       ...,
       [0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237],
       [0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237],
       [0.03397237, 0.03397237, 0.03397237, ..., 0.03397237, 0.03397237,
        0.03397237]])

In [39]:
x = np.array([[3,6,4],[4,2,6],[5,7,2]])
x.shape

(3, 3)

In [32]:

mean= np.mean(x, axis = 0)
cov = np.dot((x-mean).T, (x-mean))
cov

array([[  2.,   1.,  -2.],
       [  1.,  14., -10.],
       [ -2., -10.,   8.]])

In [34]:
np.cov(x.T, bias = True)

array([[ 0.66666667,  0.33333333, -0.66666667],
       [ 0.33333333,  4.66666667, -3.33333333],
       [-0.66666667, -3.33333333,  2.66666667]])

In [40]:
np.mean(x)

4.333333333333333